
Neos:
  Neos:
    userInterface:
      routeAfterLogin:
        values:
          '@package': 'Neos.Neos.Ui'
          '@controller': 'Backend'
          '@action': 'index'
# New support for width and height of the preview mode:
#      editPreviewModes:
#        rawContent:
#          width: 300px
#          height: 600px
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            typeConverter: Neos\Neos\Ui\TypeConverter\UiDependentImageSerializer
      translation:
        autoInclude:
          'Neos.Neos.Ui':
            - Main
    fusion:
      autoInclude:
        Neos.Neos.Ui: true
    Ui:

      # API: "start 100" and smaller numbers; "no numbers", ...
      resources:

        javascript:
          'Neos.Neos.UI:Vendor':
            resource: '${"resource://" + Neos.Ui.StaticResources.compiledResourcePackage() + "/Public/JavaScript/Vendor.js"}'
            position: 'start 1000'
          'Neos.Neos.UI:Host':
            resource: '${"resource://" + Neos.Ui.StaticResources.compiledResourcePackage() + "/Public/JavaScript/Host.js"}'
            position: 'start 900'

        stylesheets:
          'Neos.Neos.UI:Host':
            resource: '${"resource://" + Neos.Ui.StaticResources.compiledResourcePackage() + "/Public/Styles/Host.css"}'
            position: 'start 1000'
          'Neos.Neos.UI:HostOnlyStyles':
            resource: '${"resource://" + Neos.Ui.StaticResources.compiledResourcePackage() + "/Public/Styles/HostOnlyStyles.css"}'
            position: 'start 900'

      contentCanvas:
        backgroundColor: '#ffffff'

      frontendConfiguration:
        editPreviewModes: '${Neos.Ui.PositionalArraySorter.sort(Configuration.setting(''Neos.Neos.userInterface.editPreviewModes''))}'
        # You may use this place to deliver some configuration to your custom UI components, e.g.:
        # 'Your.Own:Package':
        #   someKey: someValue

        legacy:
          enableUiSwitch: false

      #################################
      # INTERNAL CONFIG (no API)
      #################################
      frontendDevelopmentMode: false
      nodeTypeRoles:
        document: 'Neos.Neos:Document'
        content: 'Neos.Neos:Content'
        contentCollection: 'Neos.Neos:ContentCollection'
      configurationDefaultEelContext:
        String: Neos\Eel\Helper\StringHelper
        Array: Neos\Eel\Helper\ArrayHelper
        Date: Neos\Eel\Helper\DateHelper
        Configuration: Neos\Eel\Helper\ConfigurationHelper
        Math: Neos\Eel\Helper\MathHelper
        Json: Neos\Eel\Helper\JsonHelper
        I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
        Neos.Ui.Workspace: Neos\Neos\Ui\Fusion\Helper\WorkspaceHelper
        Neos.Ui.NodeInfo: Neos\Neos\Ui\Fusion\Helper\NodeInfoHelper
        Neos.Ui.ContentDimensions: Neos\Neos\Ui\Fusion\Helper\ContentDimensionsHelper
        Neos.Ui.StaticResources: Neos\Neos\Ui\Fusion\Helper\StaticResourcesHelper
        Neos.Ui.PositionalArraySorter: Neos\Neos\Ui\Fusion\Helper\PositionalArraySorterHelper
      documentNodeInformation:
        metaData:
          contextPath: '${Neos.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
          siteNode: '${Neos.Ui.NodeInfo.serializedNodeAddress(site)}'
          # TODO Fix!
          #previewUrl: '${Neos.Ui.NodeInfo.uri(q(documentNode).context({workspaceName: documentNode.context.workspace.baseWorkspace.name}).get(0), controllerContext)}'
          contentDimensions:
            active: '${documentNode.dimensionSpacePoint.toLegacyDimensionArray()}'
            allowedPresets: '${Neos.Ui.ContentDimensions.allowedPresetsByName(documentNode.context.dimensions)}'
          documentNodeSerialization: '${Neos.Ui.NodeInfo.renderNode(documentNode, subgraph, controllerContext)}'
          url: '${Neos.Ui.NodeInfo.uri(Neos.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'
          dimensionSpacePoint: '${documentNode.context.contentSubgraph.dimensionSpacePoint.serializeForUri()}'
          workspaceName: '${documentNode.context.workspaceName}'
          documentNodeAggregateIdentifier: '${documentNode.nodeAggregateIdentifier}'
      initialState:
        changes:
          pending: {  }
          processing: {  }
          failed: {  }
        cr:
          nodes:
            byContextPath: '${Neos.Ui.NodeInfo.defaultNodesForBackend(site, documentNode, subgraph, controllerContext)}'
            siteNode: '${Neos.Ui.NodeInfo.serializedNodeAddress(site)}'
          contentDimensions:
            byName: '${Neos.Ui.ContentDimensions.contentDimensionsByName()}'
            active: '${subgraph.dimensionSpacePoint.coordinates}'
            allowedPresets: '${Neos.Ui.ContentDimensions.allowedPresetsByName(documentNode.context.dimensions)}'
          workspaces:
            personalWorkspace: '${Neos.Ui.Workspace.getPersonalWorkspace()}'
        ui:
          contentCanvas:
            src: '${Neos.Ui.NodeInfo.uri(Neos.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'
            contextPath: '${Neos.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
            backgroundColor: '${Configuration.setting(''Neos.Neos.Ui.contentCanvas.backgroundColor'')}'
          debugMode: false
          editPreviewMode: '${q(user).property("preferences.preferences")["contentEditing.editPreviewMode"] || Configuration.setting(''Neos.Neos.userInterface.defaultEditPreviewMode'')}'
          fullScreen:
            isFullScreen: false
          editModePanel:
            isHidden: true
          leftSideBar:
            isHidden: false
            contentTree:
              isHidden: true
          rightSideBar:
            isHidden: false
          addNodeModal:
            referenceNode: ''
            mode: insert
          drawer:
            isHidden: true
          pageTree:
            isLoading: false
            hasError: false
            focused: '${Neos.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
            active: '${Neos.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
          remote:
            isSaving: false
            isPublishing: false
            isDiscarding: false
        user:
          name:
            title: '${q(user).property(''name.title'')}'
            firstName: '${q(user).property(''name.firstName'')}'
            middleName: '${q(user).property(''name.middleName'')}'
            lastName: '${q(user).property(''name.lastName'')}'
            otherName: '${q(user).property(''name.otherName'')}'
            fullName: '${q(user).property(''name.fullName'')}'
          preferences:
            interfaceLanguage: '${q(user).property(''preferences.interfaceLanguage'')}'
          settings:
            isAutoPublishingEnabled: false
            targetWorkspace: 'live'
      changes:
        types:
          'Neos.Neos.Ui:Property': Neos\Neos\Ui\Domain\Model\Changes\Property
          'Neos.Neos.Ui:CreateInto': Neos\Neos\Ui\Domain\Model\Changes\Create
          'Neos.Neos.Ui:CreateBefore': Neos\Neos\Ui\Domain\Model\Changes\CreateBefore
          'Neos.Neos.Ui:CreateAfter': Neos\Neos\Ui\Domain\Model\Changes\CreateAfter
          'Neos.Neos.Ui:RemoveNode': Neos\Neos\Ui\Domain\Model\Changes\Remove
          'Neos.Neos.Ui:CopyBefore': Neos\Neos\Ui\Domain\Model\Changes\CopyBefore
          'Neos.Neos.Ui:CopyAfter': Neos\Neos\Ui\Domain\Model\Changes\CopyAfter
          'Neos.Neos.Ui:CopyInto': Neos\Neos\Ui\Domain\Model\Changes\CopyInto
          'Neos.Neos.Ui:MoveBefore': Neos\Neos\Ui\Domain\Model\Changes\MoveBefore
          'Neos.Neos.Ui:MoveAfter': Neos\Neos\Ui\Domain\Model\Changes\MoveAfter
          'Neos.Neos.Ui:MoveInto': Neos\Neos\Ui\Domain\Model\Changes\MoveInto
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Neos.Neos.Ui:BackendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Neos\Ui\Controller\.*'
    mvc:
      routes:
        'Neos.Neos.Ui':
          position: 'before Neos.Neos'
  Fusion:
    defaultContext:
      Neos.Ui.Activation: Neos\Neos\Ui\Fusion\Helper\ActivationHelper
      Neos.Ui.Sites: Neos\Neos\Ui\Fusion\Helper\SitesHelper
      Neos.Ui.Modules: Neos\Neos\Ui\Fusion\Helper\ModulesHelper
      Neos.Ui.Workspace: Neos\Neos\Ui\Fusion\Helper\WorkspaceHelper
      Neos.Ui.StaticResources: Neos\Neos\Ui\Fusion\Helper\StaticResourcesHelper
      Neos.Ui.PositionalArraySorter: Neos\Neos\Ui\Fusion\Helper\PositionalArraySorterHelper
      Neos.Ui.NodeInfo: Neos\Neos\Ui\Fusion\Helper\NodeInfoHelper
